/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/components/header/header.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './header.component.sass.shim.ngstyle';
export class Wrapper_HeaderComponent {
  /*private*/ _eventHandler:Function;
  context:import0.HeaderComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.HeaderComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_HeaderComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_HeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.HeaderComponent>;
  _HeaderComponent_0_3:Wrapper_HeaderComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeaderComponent_Host0,renderType_HeaderComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-header',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._HeaderComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const HeaderComponentNgFactory:import7.ComponentFactory<import0.HeaderComponent> = new import7.ComponentFactory<import0.HeaderComponent>('app-header',View_HeaderComponent_Host0,import0.HeaderComponent);
const styles_HeaderComponent:any[] = [import8.styles];
var renderType_HeaderComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_HeaderComponent,{});
export class View_HeaderComponent0 extends import1.AppView<import0.HeaderComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _el_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _el_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeaderComponent0,renderType_HeaderComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'header',new import3.InlineArray2(2,'id','header'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','header'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'nav',new import3.InlineArray2(2,'class','navbar navbar-default'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._text_6 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n					',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'button',new import3.InlineArray8(8,'class','navbar-toggle collapsed','data-target','#bs-example-navbar-collapse-1','data-toggle','collapse','type','button'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n						',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Toggle navigation',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n						',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_9,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_15 = this.renderer.createText(this._el_9,'\n						',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_9,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_17 = this.renderer.createText(this._el_9,'\n						',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_9,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_19 = this.renderer.createText(this._el_9,'\n					',(null as any));
    this._text_20 = this.renderer.createText(this._el_7,'\n					',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_7,'a',new import3.InlineArray4(4,'class','navbar-brand','href','#'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n						',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'img',new import3.InlineArray8(6,'alt','растение помидор','class','logo','src','./image/logo.svg'),(null as any));
    this._text_24 = this.renderer.createText(this._el_21,'\n					',(null as any));
    this._text_25 = this.renderer.createText(this._el_7,'\n				',(null as any));
    this._text_26 = this.renderer.createText(this._el_4,'\n\n				',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray4(4,'class','collapse navbar-collapse','id','bs-example-navbar-collapse-1'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n					',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'ul',new import3.InlineArray2(2,'class','nav navbar-nav navbar-right'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n						',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'li',new import3.InlineArray2(2,'class',''),(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_31,'a',new import3.InlineArray2(2,'href','#Rassadi'),(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_32,'span',new import3.InlineArray2(2,'class','glyphicon glyphicon-leaf'),(null as any));
    this._text_34 = this.renderer.createText(this._el_32,' Рассады',(null as any));
    this._text_35 = this.renderer.createText(this._el_29,'\n						',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_29,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n							',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'a',new import3.InlineArray2(2,'href','/shop-cart'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n								',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-shopping-cart fa-lg'),(null as any));
    this._text_41 = this.renderer.createText(this._el_38,'\n							 Корзина\n							',(null as any));
    this._text_42 = this.renderer.createText(this._el_36,'\n						',(null as any));
    this._text_43 = this.renderer.createText(this._el_29,'\n						',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_29,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_44,'a',new import3.InlineArray2(2,'href','#Contact'),(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_45,'span',new import3.InlineArray2(2,'class','glyphicon glyphicon-phone-alt'),(null as any));
    this._text_47 = this.renderer.createText(this._el_45,' Контакты',(null as any));
    this._text_48 = this.renderer.createText(this._el_29,'\n					',(null as any));
    this._text_49 = this.renderer.createText(this._el_27,'\n\n				',(null as any));
    this._text_50 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._text_51 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._text_52 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','head_title'),(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'\n			',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_53,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'Рассады',(null as any));
    this._text_57 = this.renderer.createText(this._el_53,'\n			',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_53,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'Помидор',(null as any));
    this._text_60 = this.renderer.createText(this._el_53,'\n		',(null as any));
    this._text_61 = this.renderer.createText(this._el_2,'\n\n\n	',(null as any));
    this._text_62 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_63 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._el_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._el_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63
    ]
    ),(null as any));
    return (null as any);
  }
}