/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.pay-section\n	margin: 20px 5px 0 5px\n.jumbotron\n	background: linear-gradient(to left,  rgba(0, 173, 76, 1), #007031)\n	color: #333'];