/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/components/pay-system/pay-system.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../app/services/shop-cart.service';
import * as import9 from './pay-system.component.sass.shim.ngstyle';
import * as import10 from '@angular/core/src/change_detection/change_detection_util';
export class Wrapper_PaySystemComponent {
  /*private*/ _eventHandler:Function;
  context:import0.PaySystemComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.PaySystemComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_PaySystemComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_PaySystemComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.PaySystemComponent>;
  _PaySystemComponent_0_3:Wrapper_PaySystemComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PaySystemComponent_Host0,renderType_PaySystemComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-pay-system',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_PaySystemComponent0(this.viewUtils,this,0,this._el_0);
    this._PaySystemComponent_0_3 = new Wrapper_PaySystemComponent(this.injectorGet(import8.ShopCartService,this.parentIndex));
    this.compView_0.create(this._PaySystemComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._PaySystemComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PaySystemComponent) && (0 === requestNodeIndex))) { return this._PaySystemComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PaySystemComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PaySystemComponentNgFactory:import7.ComponentFactory<import0.PaySystemComponent> = new import7.ComponentFactory<import0.PaySystemComponent>('app-pay-system',View_PaySystemComponent_Host0,import0.PaySystemComponent);
const styles_PaySystemComponent:any[] = [import9.styles];
var renderType_PaySystemComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_PaySystemComponent,{});
export class View_PaySystemComponent0 extends import1.AppView<import0.PaySystemComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  /*private*/ _expr_52:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PaySystemComponent0,renderType_PaySystemComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_52 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'section',new import3.InlineArray2(2,'class','pay-section'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','jumbotron col-xs-12 col-sm-6 col-md-4'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'form',new import3.InlineArray8(6,'action','https://money.yandex.ru/quickpay/confirm.xml','method','POST','ngNoForm',''),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,' \n					',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'input',new import3.InlineArray8(6,'name','receiver','type','hidden','value','410015185590859'),(null as any));
    this._text_11 = this.renderer.createText(this._el_8,' \n					',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n					',(null as any));
    this._text_13 = this.renderer.createText(this._el_8,'\n					',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_8,'input',new import3.InlineArray8(6,'name','label','type','hidden','value','$order_id'),(null as any));
    this._text_15 = this.renderer.createText(this._el_8,' \n					',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_8,'input',new import3.InlineArray8(6,'name','quickpay-form','type','hidden','value','shop'),(null as any));
    this._text_17 = this.renderer.createText(this._el_8,' \n					',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_8,'input',new import3.InlineArray8(6,'name','successURL','type','hidden','value','/shop-cart'),(null as any));
    this._text_19 = this.renderer.createText(this._el_8,' \n					',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_8,'input',new import3.InlineArray8(6,'name','targets','type','hidden','value','транзакция {order_id}'),(null as any));
    this._text_21 = this.renderer.createText(this._el_8,' \n					',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','input-group'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n					',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'input',new import3.InlineArray16(10,'class','form-control','data-type','number','name','sum','readonly','','type','text'),(null as any));
    this._text_25 = this.renderer.createText(this._el_22,'\n					',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_22,'div',new import3.InlineArray2(2,'class','input-group-addon'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'руб.',(null as any));
    this._text_28 = this.renderer.createText(this._el_22,'\n					',(null as any));
    this._text_29 = this.renderer.createText(this._el_8,'\n					',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','checkbox'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n						',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_32,'input',new import3.InlineArray8(8,'checked','','name','paymentType','type','radio','value','AC'),(null as any));
    this._text_34 = this.renderer.createText(this._el_32,'Банковской картой',(null as any));
    this._text_35 = this.renderer.createText(this._el_30,' \n						',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_30,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_36,'input',new import3.InlineArray8(6,'name','paymentType','type','radio','value','PC'),(null as any));
    this._text_38 = this.renderer.createText(this._el_36,'Яндекс.Деньгами',(null as any));
    this._text_39 = this.renderer.createText(this._el_30,' \n						',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_30,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_40,'input',new import3.InlineArray8(6,'name','paymentType','type','radio','value','MC'),(null as any));
    this._text_42 = this.renderer.createText(this._el_40,'С Мобильного',(null as any));
    this._text_43 = this.renderer.createText(this._el_30,' \n					',(null as any));
    this._text_44 = this.renderer.createText(this._el_8,'\n					',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_8,'input',new import3.InlineArray8(6,'class','btn btn-default','type','submit','value','Оплатить'),(null as any));
    this._text_46 = this.renderer.createText(this._el_8,' \n				',(null as any));
    this._text_47 = this.renderer.createText(this._el_6,'\n			',(null as any));
    this._text_48 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._text_49 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_50 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_51 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_52:any = import3.inlineInterpolate(1,'',this.context.moneyCheck,'');
    if (import3.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementProperty(this._el_24,'value',currVal_52);
      this._expr_52 = currVal_52;
    }
  }
}