/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/components/main/main.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './main.component.css.shim.ngstyle';
import * as import9 from '../../../../app/components/header/header.component';
import * as import10 from '../header/header.component.ngfactory';
import * as import11 from '../../../../app/components/section/section.component';
import * as import12 from '../section/section.component.ngfactory';
import * as import13 from '../../../../app/components/footer/footer.component';
import * as import14 from '../footer/footer.component.ngfactory';
import * as import15 from '../../../../app/services/gallery.service';
import * as import16 from '../../../../app/services/shop-cart.service';
export class Wrapper_MainComponent {
  /*private*/ _eventHandler:Function;
  context:import0.MainComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.MainComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_MainComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_MainComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.MainComponent>;
  _MainComponent_0_3:Wrapper_MainComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MainComponent_Host0,renderType_MainComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-main',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_MainComponent0(this.viewUtils,this,0,this._el_0);
    this._MainComponent_0_3 = new Wrapper_MainComponent();
    this.compView_0.create(this._MainComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._MainComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MainComponent) && (0 === requestNodeIndex))) { return this._MainComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MainComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const MainComponentNgFactory:import7.ComponentFactory<import0.MainComponent> = new import7.ComponentFactory<import0.MainComponent>('app-main',View_MainComponent_Host0,import0.MainComponent);
const styles_MainComponent:any[] = [import8.styles];
var renderType_MainComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_MainComponent,{});
export class View_MainComponent0 extends import1.AppView<import0.MainComponent> {
  _el_0:any;
  compView_0:import1.AppView<import9.HeaderComponent>;
  _HeaderComponent_0_3:import10.Wrapper_HeaderComponent;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import11.SectionComponent>;
  _SectionComponent_2_3:import12.Wrapper_SectionComponent;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import13.FooterComponent>;
  _FooterComponent_4_3:import14.Wrapper_FooterComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MainComponent0,renderType_MainComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'app-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import10.View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new import10.Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'app-section',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import12.View_SectionComponent0(this.viewUtils,this,2,this._el_2);
    this._SectionComponent_2_3 = new import12.Wrapper_SectionComponent(this.parentView.injectorGet(import15.GalleryService,this.parentIndex),this.parentView.injectorGet(import16.ShopCartService,this.parentIndex));
    this.compView_2.create(this._SectionComponent_2_3.context);
    this._text_3 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,parentRenderNode,'app-footer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import14.View_FooterComponent0(this.viewUtils,this,4,this._el_4);
    this._FooterComponent_4_3 = new import14.Wrapper_FooterComponent();
    this.compView_4.create(this._FooterComponent_4_3.context);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    if (((token === import11.SectionComponent) && (2 === requestNodeIndex))) { return this._SectionComponent_2_3.context; }
    if (((token === import13.FooterComponent) && (4 === requestNodeIndex))) { return this._FooterComponent_4_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._SectionComponent_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._FooterComponent_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_4.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this.compView_2.destroy();
    this.compView_4.destroy();
  }
}