/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/components/section/section.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../app/services/gallery.service';
import * as import9 from '../../../../app/services/shop-cart.service';
import * as import10 from './section.component.sass.shim.ngstyle';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import13 from '@angular/core/src/change_detection/change_detection_util';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '@angular/common/src/directives/ng_if';
import * as import16 from '@angular/core/src/security';
import * as import17 from '../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import18 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import19 from '../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import20 from '../../../node_modules/@angular/forms/src/directives/number_value_accessor.ngfactory';
import * as import21 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import22 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import25 from '@angular/forms/src/directives/default_value_accessor';
import * as import26 from '@angular/forms/src/directives/number_value_accessor';
import * as import27 from '@angular/forms/src/directives/control_value_accessor';
import * as import28 from '@angular/forms/src/directives/ng_model';
import * as import29 from '@angular/forms/src/directives/ng_control';
import * as import30 from '@angular/forms/src/directives/ng_control_status';
import * as import31 from '@angular/forms/src/directives/ng_form';
import * as import32 from '@angular/forms/src/directives/control_container';
import * as import33 from '@angular/common/src/directives/ng_for';
export class Wrapper_SectionComponent {
  /*private*/ _eventHandler:Function;
  context:import0.SectionComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.SectionComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_SectionComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_SectionComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.SectionComponent>;
  _SectionComponent_0_3:Wrapper_SectionComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SectionComponent_Host0,renderType_SectionComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-section',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_SectionComponent0(this.viewUtils,this,0,this._el_0);
    this._SectionComponent_0_3 = new Wrapper_SectionComponent(this.injectorGet(import8.GalleryService,this.parentIndex),this.injectorGet(import9.ShopCartService,this.parentIndex));
    this.compView_0.create(this._SectionComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._SectionComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SectionComponent) && (0 === requestNodeIndex))) { return this._SectionComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SectionComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const SectionComponentNgFactory:import7.ComponentFactory<import0.SectionComponent> = new import7.ComponentFactory<import0.SectionComponent>('app-section',View_SectionComponent_Host0,import0.SectionComponent);
const styles_SectionComponent:any[] = [import10.styles];
class View_SectionComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_SectionComponent1,renderType_SectionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'a',new import3.InlineArray4(4,'class','shop-cart','href','/shop-cart'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n										',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-arrow-right fa-lg'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n										',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-shopping-cart fa-lg'),(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n									',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_SectionComponent3 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_SectionComponent3,renderType_SectionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','clearfix'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_SectionComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _anchor_38:any;
  /*private*/ _vc_38:import11.ViewContainer;
  _TemplateRef_38_5:any;
  _NgIf_38_6:import12.Wrapper_NgIf;
  _text_39:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_SectionComponent2,renderType_SectionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_43 = import13.UNINITIALIZED;
    this._expr_44 = import13.UNINITIALIZED;
    this._expr_45 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._text_1 = this.renderer.createText((null as any),'\n						',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','col-sm-4 col-xs-12'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n							',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','cart shadow'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n								',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'h3',new import3.InlineArray2(2,'class','cart-name'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n								',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','cart-body'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n									',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n										',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray4(4,'class','col-xs-12','id','cart-size'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n											',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'img',new import3.InlineArray4(4,'alt','','class','show img-responsive'),(null as any));
    this._text_16 = this.renderer.createText(this._el_13,'\n											',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_13,'img',new import3.InlineArray4(4,'alt','','class','hide img-responsive'),(null as any));
    this._text_18 = this.renderer.createText(this._el_13,'\n											',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_13,'i',new import3.InlineArray4(4,'aria-hidden','true','class','cart-size fa fa-search-plus fa-2x'),(null as any));
    this._text_20 = this.renderer.createText(this._el_13,'\n										',(null as any));
    this._text_21 = this.renderer.createText(this._el_11,'\n										',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','clearfix visible-xs-block'),(null as any));
    this._text_23 = this.renderer.createText(this._el_11,'\n										',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','col-xs-6'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n											',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'div',new import3.InlineArray2(2,'class','tom shadow-hover'),(null as any));
    this._text_27 = this.renderer.createText(this._el_24,'\n										',(null as any));
    this._text_28 = this.renderer.createText(this._el_11,'\n										',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','col-xs-6'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n											',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'div',new import3.InlineArray2(2,'class','ras shadow-hover'),(null as any));
    this._text_32 = this.renderer.createText(this._el_29,'\n										',(null as any));
    this._text_33 = this.renderer.createText(this._el_11,'\n									',(null as any));
    this._text_34 = this.renderer.createText(this._el_9,'\n								',(null as any));
    this._text_35 = this.renderer.createText(this._el_4,'\n							',(null as any));
    this._text_36 = this.renderer.createText(this._el_2,'\n						',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n						',(null as any));
    this._anchor_38 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_38 = new import11.ViewContainer(38,0,this,this._anchor_38);
    this._TemplateRef_38_5 = new import14.TemplateRef_(this,38,this._anchor_38);
    this._NgIf_38_6 = new import12.Wrapper_NgIf(this._vc_38.vcRef,this._TemplateRef_38_5);
    this._text_39 = this.renderer.createText((null as any),'\n					',(null as any));
    this.init(this._text_39,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._anchor_38,
      this._text_39
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (38 === requestNodeIndex))) { return this._TemplateRef_38_5; }
    if (((token === import15.NgIf) && (38 === requestNodeIndex))) { return this._NgIf_38_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_38_0_0:any = ((this.parentView.context.i % 3) == 2);
    this._NgIf_38_6.check_ngIf(currVal_38_0_0,throwOnChange,false);
    this._NgIf_38_6.ngDoCheck(this,this._anchor_38,throwOnChange);
    this._vc_38.detectChangesInNestedViews(throwOnChange);
    const currVal_43:any = import3.inlineInterpolate(1,'',this.context.$implicit.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setText(this._text_7,currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = import3.inlineInterpolate(2,'',this.context.$implicit.path,'',this.context.$implicit.urlTom,'');
    if (import3.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementProperty(this._el_15,'src',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_44));
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = import3.inlineInterpolate(2,'',this.context.$implicit.path,'',this.context.$implicit.urlRas,'');
    if (import3.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementProperty(this._el_17,'src',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_45));
      this._expr_45 = currVal_45;
    }
  }
  destroyInternal():void {
    this._vc_38.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
    cb(this._text_1,ctx);
    cb(this._el_2,ctx);
    cb(this._text_37,ctx);
    cb(this._vc_38.nativeElement,ctx);
    this._vc_38.visitNestedViewRootNodes(cb,ctx);
    cb(this._text_39,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 38)) { return new View_SectionComponent3(this.viewUtils,this,38,this._anchor_38,this._vc_38); }
    return (null as any);
  }
}
var renderType_SectionComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_SectionComponent,{});
export class View_SectionComponent0 extends import1.AppView<import0.SectionComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _el_99:any;
  _text_100:any;
  _el_101:any;
  _text_102:any;
  _text_103:any;
  _el_104:any;
  _text_105:any;
  _text_106:any;
  _el_107:any;
  _text_108:any;
  _text_109:any;
  _text_110:any;
  _text_111:any;
  _text_112:any;
  _text_113:any;
  _text_114:any;
  _el_115:any;
  _text_116:any;
  _el_117:any;
  _text_118:any;
  _text_119:any;
  _text_120:any;
  _text_121:any;
  _el_122:any;
  _text_123:any;
  _el_124:any;
  _text_125:any;
  _el_126:any;
  _text_127:any;
  _el_128:any;
  _text_129:any;
  _text_130:any;
  _el_131:any;
  _text_132:any;
  _el_133:any;
  _NgForm_133_3:import17.Wrapper_NgForm;
  _ControlContainer_133_4:any;
  _NgControlStatusGroup_133_5:import18.Wrapper_NgControlStatusGroup;
  _text_134:any;
  _el_135:any;
  _text_136:any;
  _el_137:any;
  _text_138:any;
  _text_139:any;
  _el_140:any;
  _text_141:any;
  _el_142:any;
  _text_143:any;
  _text_144:any;
  _el_145:any;
  _text_146:any;
  _el_147:any;
  _text_148:any;
  _el_149:any;
  _text_150:any;
  _text_151:any;
  _el_152:any;
  _text_153:any;
  _el_154:any;
  _text_155:any;
  _text_156:any;
  _el_157:any;
  _text_158:any;
  _el_159:any;
  _text_160:any;
  _el_161:any;
  _text_162:any;
  _text_163:any;
  _text_164:any;
  _text_165:any;
  _text_166:any;
  _text_167:any;
  _el_168:any;
  _text_169:any;
  _el_170:any;
  _text_171:any;
  _text_172:any;
  _el_173:any;
  _DefaultValueAccessor_173_3:import19.Wrapper_DefaultValueAccessor;
  _NumberValueAccessor_173_4:import20.Wrapper_NumberValueAccessor;
  _NG_VALUE_ACCESSOR_173_5:any[];
  _NgModel_173_6:import21.Wrapper_NgModel;
  _NgControl_173_7:any;
  _NgControlStatus_173_8:import18.Wrapper_NgControlStatus;
  _text_174:any;
  _el_175:any;
  _text_176:any;
  _el_177:any;
  _text_178:any;
  _text_179:any;
  _el_180:any;
  _text_181:any;
  _text_182:any;
  _el_183:any;
  _text_184:any;
  _el_185:any;
  _text_186:any;
  _text_187:any;
  _anchor_188:any;
  /*private*/ _vc_188:import11.ViewContainer;
  _TemplateRef_188_5:any;
  _NgIf_188_6:import12.Wrapper_NgIf;
  _text_189:any;
  _text_190:any;
  _text_191:any;
  _text_192:any;
  _text_193:any;
  _text_194:any;
  _text_195:any;
  _text_196:any;
  _el_197:any;
  _text_198:any;
  _el_199:any;
  _text_200:any;
  _el_201:any;
  _text_202:any;
  _el_203:any;
  _text_204:any;
  _text_205:any;
  _el_206:any;
  _text_207:any;
  _el_208:any;
  _text_209:any;
  _el_210:any;
  _text_211:any;
  _el_212:any;
  _text_213:any;
  _text_214:any;
  _el_215:any;
  _text_216:any;
  _text_217:any;
  _el_218:any;
  _text_219:any;
  _text_220:any;
  _el_221:any;
  _text_222:any;
  _el_223:any;
  _text_224:any;
  _text_225:any;
  _text_226:any;
  _text_227:any;
  _el_228:any;
  _text_229:any;
  _el_230:any;
  _text_231:any;
  _text_232:any;
  _text_233:any;
  _text_234:any;
  _el_235:any;
  _text_236:any;
  _el_237:any;
  _text_238:any;
  _el_239:any;
  _text_240:any;
  _el_241:any;
  _text_242:any;
  _text_243:any;
  _el_244:any;
  _text_245:any;
  _el_246:any;
  _text_247:any;
  _anchor_248:any;
  /*private*/ _vc_248:import11.ViewContainer;
  _TemplateRef_248_5:any;
  _NgFor_248_6:import22.Wrapper_NgFor;
  _text_249:any;
  _text_250:any;
  _text_251:any;
  _text_252:any;
  _text_253:any;
  _text_254:any;
  _el_255:any;
  _text_256:any;
  _el_257:any;
  _text_258:any;
  _el_259:any;
  _text_260:any;
  _el_261:any;
  _text_262:any;
  _el_263:any;
  _text_264:any;
  _el_265:any;
  _text_266:any;
  _text_267:any;
  _el_268:any;
  _text_269:any;
  _el_270:any;
  _text_271:any;
  _el_272:any;
  _text_273:any;
  _text_274:any;
  _el_275:any;
  _text_276:any;
  _el_277:any;
  _text_278:any;
  _el_279:any;
  _text_280:any;
  _el_281:any;
  _text_282:any;
  _el_283:any;
  _text_284:any;
  _el_285:any;
  _text_286:any;
  _text_287:any;
  _text_288:any;
  _el_289:any;
  _text_290:any;
  _el_291:any;
  _el_292:any;
  _text_293:any;
  _text_294:any;
  _text_295:any;
  _text_296:any;
  _text_297:any;
  _text_298:any;
  _el_299:any;
  _text_300:any;
  _el_301:any;
  _text_302:any;
  _el_303:any;
  _text_304:any;
  _el_305:any;
  _text_306:any;
  _el_307:any;
  _text_308:any;
  _text_309:any;
  _text_310:any;
  _el_311:any;
  _text_312:any;
  _el_313:any;
  _el_314:any;
  _text_315:any;
  _text_316:any;
  _text_317:any;
  _text_318:any;
  _text_319:any;
  _text_320:any;
  _el_321:any;
  _text_322:any;
  _el_323:any;
  _text_324:any;
  _el_325:any;
  _text_326:any;
  _el_327:any;
  _text_328:any;
  _el_329:any;
  _text_330:any;
  _text_331:any;
  _text_332:any;
  _el_333:any;
  _text_334:any;
  _el_335:any;
  _el_336:any;
  _text_337:any;
  _text_338:any;
  _text_339:any;
  _text_340:any;
  _text_341:any;
  _text_342:any;
  _el_343:any;
  _text_344:any;
  _el_345:any;
  _text_346:any;
  _el_347:any;
  _text_348:any;
  _el_349:any;
  _text_350:any;
  _el_351:any;
  _text_352:any;
  _text_353:any;
  _text_354:any;
  _el_355:any;
  _text_356:any;
  _el_357:any;
  _el_358:any;
  _text_359:any;
  _text_360:any;
  _text_361:any;
  _text_362:any;
  _text_363:any;
  _text_364:any;
  _text_365:any;
  _text_366:any;
  _text_367:any;
  _el_368:any;
  _text_369:any;
  _el_370:any;
  _text_371:any;
  _text_372:any;
  _text_373:any;
  _text_374:any;
  _text_375:any;
  _text_376:any;
  _el_377:any;
  _text_378:any;
  _el_379:any;
  _text_380:any;
  _el_381:any;
  _text_382:any;
  _el_383:any;
  _text_384:any;
  _el_385:any;
  _text_386:any;
  _text_387:any;
  _text_388:any;
  _el_389:any;
  _text_390:any;
  _el_391:any;
  _text_392:any;
  _el_393:any;
  _text_394:any;
  _el_395:any;
  _text_396:any;
  _el_397:any;
  _text_398:any;
  _el_399:any;
  _text_400:any;
  _text_401:any;
  _text_402:any;
  _el_403:any;
  _text_404:any;
  _el_405:any;
  _text_406:any;
  _el_407:any;
  _text_408:any;
  _el_409:any;
  _text_410:any;
  _text_411:any;
  _text_412:any;
  _el_413:any;
  _text_414:any;
  _el_415:any;
  _text_416:any;
  _el_417:any;
  _text_418:any;
  _el_419:any;
  _text_420:any;
  _text_421:any;
  _text_422:any;
  _el_423:any;
  _text_424:any;
  _el_425:any;
  _text_426:any;
  _el_427:any;
  _text_428:any;
  _el_429:any;
  _text_430:any;
  _text_431:any;
  _text_432:any;
  _text_433:any;
  _text_434:any;
  _text_435:any;
  _text_436:any;
  /*private*/ _expr_452:any;
  /*private*/ _expr_453:any;
  /*private*/ _expr_454:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SectionComponent0,renderType_SectionComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_452 = import13.UNINITIALIZED;
    this._expr_453 = import13.UNINITIALIZED;
    this._expr_454 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'section',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n			\n			',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','slider'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-md-2 col-sm-2'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','rassada-img rassada-img-up'),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-sm-8 col-xs-12 sl-tr-rel'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n					',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','sl-text'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n						',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Здоровая рассада помидор – гарантия обильного урожая томатов. Ошибки, которые допускают начинающие огородники на стадии посева семян и взращивания рассады, обязательно скажутся на плодоношении взрослого растения. В этом деле мелочей быть не может',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n					',(null as any));
    this._text_16 = this.renderer.createText(this._el_9,'\n					',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','sl-text'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n						',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Рассады в торфяных и пластиковых горшочках на посадку в теплицу или на открытом месте при благоприятном климате',(null as any));
    this._text_21 = this.renderer.createText(this._el_17,'\n					',(null as any));
    this._text_22 = this.renderer.createText(this._el_9,'\n					',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','sl-text'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n						',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Лучшие условия для томатов это тепличные условия',(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n					',(null as any));
    this._text_28 = this.renderer.createText(this._el_9,'\n					',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','sl-text'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n						',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Хороший урожай вкусных сочных томатов',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n					',(null as any));
    this._text_34 = this.renderer.createText(this._el_9,'\n					',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','sl-text'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n						',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Лучшие условия для томатов это тепличные условия',(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n					',(null as any));
    this._text_40 = this.renderer.createText(this._el_9,'\n				',(null as any));
    this._text_41 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-md-2 col-sm-2'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'\n					',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_42,'div',new import3.InlineArray2(2,'class','rassada-img rassada-img-down'),(null as any));
    this._text_45 = this.renderer.createText(this._el_42,'\n				',(null as any));
    this._text_46 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-xs-12 sl-span-center'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'\n					',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_47,'span',new import3.InlineArray2(2,'class','sl-span sl-span-1'),(null as any));
    this._text_50 = this.renderer.createText(this._el_47,'\n					',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_47,'span',new import3.InlineArray2(2,'class','sl-span sl-span-2'),(null as any));
    this._text_52 = this.renderer.createText(this._el_47,'\n					',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_47,'span',new import3.InlineArray2(2,'class','sl-span sl-span-3'),(null as any));
    this._text_54 = this.renderer.createText(this._el_47,'\n					',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_47,'span',new import3.InlineArray2(2,'class','sl-span sl-span-4'),(null as any));
    this._text_56 = this.renderer.createText(this._el_47,'\n					',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_47,'span',new import3.InlineArray2(2,'class','sl-span sl-span-5'),(null as any));
    this._text_58 = this.renderer.createText(this._el_47,'\n				',(null as any));
    this._text_59 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._text_60 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_61 = this.renderer.createText(parentRenderNode,'	\n\n',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,parentRenderNode,'section',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'\n',(null as any));
    this._text_64 = this.renderer.createText(this._el_62,'\n',(null as any));
    this._text_65 = this.renderer.createText(this._el_62,'\n',(null as any));
    this._text_66 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,parentRenderNode,'section',new import3.InlineArray2(2,'class','first-section'),(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'\n	',(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_67,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'\n		',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_69,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'\n			',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_71,'div',new import3.InlineArray2(2,'class','col-sm-8'),(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'\n				',(null as any));
    this._el_75 = import3.createRenderElement(this.renderer,this._el_73,'div',new import3.InlineArray2(2,'class','preimuch'),(null as any));
    this._text_76 = this.renderer.createText(this._el_75,'\n					',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_75,'h2',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'Прeимущества',(null as any));
    this._text_79 = this.renderer.createText(this._el_75,'\n						',(null as any));
    this._el_80 = import3.createRenderElement(this.renderer,this._el_75,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_81 = this.renderer.createText(this._el_80,'\n							',(null as any));
    this._el_82 = import3.createRenderElement(this.renderer,this._el_80,'div',new import3.InlineArray2(2,'class','col-sm-6'),(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'\n								',(null as any));
    this._el_84 = import3.createRenderElement(this.renderer,this._el_82,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'\n									',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_84,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_87 = this.renderer.createText(this._el_86,'из наших рассад Вы получите богатый урожай томатов',(null as any));
    this._text_88 = this.renderer.createText(this._el_84,'\n									',(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,this._el_84,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'не мучайте себя постоянными пересадками рассады в горшки, этот долгий процесс мы берем на себя',(null as any));
    this._text_91 = this.renderer.createText(this._el_84,'\n									',(null as any));
    this._el_92 = import3.createRenderElement(this.renderer,this._el_84,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_93 = this.renderer.createText(this._el_92,'просто выберите количество и оплатить и мы сами привезем Вам рассады',(null as any));
    this._text_94 = this.renderer.createText(this._el_84,'\n								',(null as any));
    this._text_95 = this.renderer.createText(this._el_82,'\n							',(null as any));
    this._text_96 = this.renderer.createText(this._el_80,'\n							',(null as any));
    this._el_97 = import3.createRenderElement(this.renderer,this._el_80,'div',new import3.InlineArray2(2,'class','col-sm-6'),(null as any));
    this._text_98 = this.renderer.createText(this._el_97,'\n								',(null as any));
    this._el_99 = import3.createRenderElement(this.renderer,this._el_97,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_100 = this.renderer.createText(this._el_99,'\n									',(null as any));
    this._el_101 = import3.createRenderElement(this.renderer,this._el_99,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_102 = this.renderer.createText(this._el_101,'на ранней стадии ростления растения требуют большого ухода ',(null as any));
    this._text_103 = this.renderer.createText(this._el_99,'\n									',(null as any));
    this._el_104 = import3.createRenderElement(this.renderer,this._el_99,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_105 = this.renderer.createText(this._el_104,'нет смысла загромождать дом большим количеством рассад,проще взять готовые саженцы в начале дачного сезона',(null as any));
    this._text_106 = this.renderer.createText(this._el_99,'\n									',(null as any));
    this._el_107 = import3.createRenderElement(this.renderer,this._el_99,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_108 = this.renderer.createText(this._el_107,'вечная головная боль выбора времени посадки семян, чтобы успеть в срок, а погода нам приподносит разные ситуации',(null as any));
    this._text_109 = this.renderer.createText(this._el_99,'\n								',(null as any));
    this._text_110 = this.renderer.createText(this._el_97,'\n							',(null as any));
    this._text_111 = this.renderer.createText(this._el_80,'\n					',(null as any));
    this._text_112 = this.renderer.createText(this._el_75,'\n				',(null as any));
    this._text_113 = this.renderer.createText(this._el_73,'\n			',(null as any));
    this._text_114 = this.renderer.createText(this._el_71,'\n			',(null as any));
    this._el_115 = import3.createRenderElement(this.renderer,this._el_71,'div',new import3.InlineArray2(2,'class','col-sm-4 text-center urogai'),(null as any));
    this._text_116 = this.renderer.createText(this._el_115,'\n				',(null as any));
    this._el_117 = import3.createRenderElement(this.renderer,this._el_115,'img',new import3.InlineArray4(4,'alt','урожай','src','./image/urogai.svg'),(null as any));
    this._text_118 = this.renderer.createText(this._el_115,'\n			',(null as any));
    this._text_119 = this.renderer.createText(this._el_71,'\n		',(null as any));
    this._text_120 = this.renderer.createText(this._el_69,'\n	',(null as any));
    this._text_121 = this.renderer.createText(this._el_67,'\n			',(null as any));
    this._el_122 = import3.createRenderElement(this.renderer,this._el_67,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_123 = this.renderer.createText(this._el_122,'\n				',(null as any));
    this._el_124 = import3.createRenderElement(this.renderer,this._el_122,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_125 = this.renderer.createText(this._el_124,'\n					',(null as any));
    this._el_126 = import3.createRenderElement(this.renderer,this._el_124,'div',new import3.InlineArray2(2,'class','col-sm-4 col-md-6 hidden-xs'),(null as any));
    this._text_127 = this.renderer.createText(this._el_126,'\n						',(null as any));
    this._el_128 = import3.createRenderElement(this.renderer,this._el_126,'img',new import3.InlineArray8(6,'alt','стрелка','class','img-responsive','src','./image/strelka.svg'),(null as any));
    this._text_129 = this.renderer.createText(this._el_126,'\n					',(null as any));
    this._text_130 = this.renderer.createText(this._el_124,'\n					',(null as any));
    this._el_131 = import3.createRenderElement(this.renderer,this._el_124,'div',new import3.InlineArray2(2,'class','col-sm-8 col-md-6'),(null as any));
    this._text_132 = this.renderer.createText(this._el_131,'\n						',(null as any));
    this._el_133 = import3.createRenderElement(this.renderer,this._el_131,'form',new import3.InlineArray4(4,'action','','class','order-form'),(null as any));
    this._NgForm_133_3 = new import17.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_133_4 = this._NgForm_133_3.context;
    this._NgControlStatusGroup_133_5 = new import18.Wrapper_NgControlStatusGroup(this._ControlContainer_133_4);
    this._text_134 = this.renderer.createText(this._el_133,'\n							',(null as any));
    this._el_135 = import3.createRenderElement(this.renderer,this._el_133,'fieldset',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_136 = this.renderer.createText(this._el_135,'\n								',(null as any));
    this._el_137 = import3.createRenderElement(this.renderer,this._el_135,'legend',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_138 = this.renderer.createText(this._el_137,'Быстрый заказ',(null as any));
    this._text_139 = this.renderer.createText(this._el_135,'\n								',(null as any));
    this._el_140 = import3.createRenderElement(this.renderer,this._el_135,'div',new import3.InlineArray2(2,'class','col-sm-6'),(null as any));
    this._text_141 = this.renderer.createText(this._el_140,'\n									',(null as any));
    this._el_142 = import3.createRenderElement(this.renderer,this._el_140,'label',new import3.InlineArray2(2,'for','vid'),(null as any));
    this._text_143 = this.renderer.createText(this._el_142,'Выберите сорт',(null as any));
    this._text_144 = this.renderer.createText(this._el_140,'\n									',(null as any));
    this._el_145 = import3.createRenderElement(this.renderer,this._el_140,'div',new import3.InlineArray2(2,'id','sort'),(null as any));
    this._text_146 = this.renderer.createText(this._el_145,'\n										',(null as any));
    this._el_147 = import3.createRenderElement(this.renderer,this._el_145,'button',new import3.InlineArray2(2,'class',''),(null as any));
    this._text_148 = this.renderer.createText(this._el_147,'\n											',(null as any));
    this._el_149 = import3.createRenderElement(this.renderer,this._el_147,'span',new import3.InlineArray2(2,'class','glyphicon glyphicon-menu-left'),(null as any));
    this._text_150 = this.renderer.createText(this._el_147,'\n										',(null as any));
    this._text_151 = this.renderer.createText(this._el_145,'\n										',(null as any));
    this._el_152 = import3.createRenderElement(this.renderer,this._el_145,'button',new import3.InlineArray2(2,'class',''),(null as any));
    this._text_153 = this.renderer.createText(this._el_152,'\n											',(null as any));
    this._el_154 = import3.createRenderElement(this.renderer,this._el_152,'span',new import3.InlineArray2(2,'class','glyphicon glyphicon-menu-right'),(null as any));
    this._text_155 = this.renderer.createText(this._el_152,'\n										',(null as any));
    this._text_156 = this.renderer.createText(this._el_145,'\n										',(null as any));
    this._el_157 = import3.createRenderElement(this.renderer,this._el_145,'figure',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_158 = this.renderer.createText(this._el_157,'\n											',(null as any));
    this._el_159 = import3.createRenderElement(this.renderer,this._el_157,'img',new import3.InlineArray4(4,'alt','Рассады','class','img-responsive'),(null as any));
    this._text_160 = this.renderer.createText(this._el_157,'\n											',(null as any));
    this._el_161 = import3.createRenderElement(this.renderer,this._el_157,'figcaption',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_162 = this.renderer.createText(this._el_161,'',(null as any));
    this._text_163 = this.renderer.createText(this._el_157,'\n										',(null as any));
    this._text_164 = this.renderer.createText(this._el_145,'\n										\n									',(null as any));
    this._text_165 = this.renderer.createText(this._el_140,'\n									',(null as any));
    this._text_166 = this.renderer.createText(this._el_140,'\n								',(null as any));
    this._text_167 = this.renderer.createText(this._el_135,'\n								',(null as any));
    this._el_168 = import3.createRenderElement(this.renderer,this._el_135,'div',new import3.InlineArray2(2,'class','col-sm-6'),(null as any));
    this._text_169 = this.renderer.createText(this._el_168,'\n									',(null as any));
    this._el_170 = import3.createRenderElement(this.renderer,this._el_168,'label',new import3.InlineArray2(2,'for','kol'),(null as any));
    this._text_171 = this.renderer.createText(this._el_170,'Выберите количество',(null as any));
    this._text_172 = this.renderer.createText(this._el_168,'\n									',(null as any));
    this._el_173 = import3.createRenderElement(this.renderer,this._el_168,'input',new import3.InlineArray16(10,'max','100','min','1','name','rasCount','type','number','value','1'),(null as any));
    this._DefaultValueAccessor_173_3 = new import19.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_173));
    this._NumberValueAccessor_173_4 = new import20.Wrapper_NumberValueAccessor(this.renderer,new import23.ElementRef(this._el_173));
    this._NG_VALUE_ACCESSOR_173_5 = [
      this._DefaultValueAccessor_173_3.context,
      this._NumberValueAccessor_173_4.context
    ]
    ;
    this._NgModel_173_6 = new import21.Wrapper_NgModel(this._ControlContainer_133_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_173_5);
    this._NgControl_173_7 = this._NgModel_173_6.context;
    this._NgControlStatus_173_8 = new import18.Wrapper_NgControlStatus(this._NgControl_173_7);
    this._text_174 = this.renderer.createText(this._el_168,'\n									',(null as any));
    this._el_175 = import3.createRenderElement(this.renderer,this._el_168,'h5',new import3.InlineArray4(4,'class','price','for','price'),(null as any));
    this._text_176 = this.renderer.createText(this._el_175,'',(null as any));
    this._el_177 = import3.createRenderElement(this.renderer,this._el_175,'span',new import3.InlineArray2(2,'class','glyphicons glyphicon-rub'),(null as any));
    this._text_178 = this.renderer.createText(this._el_175,'\n									',(null as any));
    this._text_179 = this.renderer.createText(this._el_168,'\n									',(null as any));
    this._el_180 = import3.createRenderElement(this.renderer,this._el_168,'label',new import3.InlineArray2(2,'for','kol'),(null as any));
    this._text_181 = this.renderer.createText(this._el_180,'Положите в корзину',(null as any));
    this._text_182 = this.renderer.createText(this._el_168,'\n									',(null as any));
    this._el_183 = import3.createRenderElement(this.renderer,this._el_168,'button',new import3.InlineArray4(4,'class','btn-tomato','type','submit'),(null as any));
    this._text_184 = this.renderer.createText(this._el_183,'\n										В корзину ',(null as any));
    this._el_185 = import3.createRenderElement(this.renderer,this._el_183,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-shopping-cart fa-lg'),(null as any));
    this._text_186 = this.renderer.createText(this._el_183,'\n									',(null as any));
    this._text_187 = this.renderer.createText(this._el_168,'\n									',(null as any));
    this._anchor_188 = this.renderer.createTemplateAnchor(this._el_168,(null as any));
    this._vc_188 = new import11.ViewContainer(188,168,this,this._anchor_188);
    this._TemplateRef_188_5 = new import14.TemplateRef_(this,188,this._anchor_188);
    this._NgIf_188_6 = new import12.Wrapper_NgIf(this._vc_188.vcRef,this._TemplateRef_188_5);
    this._text_189 = this.renderer.createText(this._el_168,'\n								',(null as any));
    this._text_190 = this.renderer.createText(this._el_135,'\n							',(null as any));
    this._text_191 = this.renderer.createText(this._el_133,'\n						',(null as any));
    this._text_192 = this.renderer.createText(this._el_131,'\n					',(null as any));
    this._text_193 = this.renderer.createText(this._el_124,'\n				',(null as any));
    this._text_194 = this.renderer.createText(this._el_122,'\n\n	',(null as any));
    this._text_195 = this.renderer.createText(this._el_67,'\n\n',(null as any));
    this._text_196 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_197 = import3.createRenderElement(this.renderer,parentRenderNode,'section',new import3.InlineArray2(2,'class','section'),(null as any));
    this._text_198 = this.renderer.createText(this._el_197,'\n	',(null as any));
    this._el_199 = import3.createRenderElement(this.renderer,this._el_197,'div',new import3.InlineArray2(2,'class','tom-container'),(null as any));
    this._text_200 = this.renderer.createText(this._el_199,'\n		',(null as any));
    this._el_201 = import3.createRenderElement(this.renderer,this._el_199,'div',new import3.InlineArray2(2,'class','col-sm-2 hidden-xs'),(null as any));
    this._text_202 = this.renderer.createText(this._el_201,'\n			',(null as any));
    this._el_203 = import3.createRenderElement(this.renderer,this._el_201,'div',new import3.InlineArray2(2,'class','rassada-img rassada-img-up'),(null as any));
    this._text_204 = this.renderer.createText(this._el_201,'\n		',(null as any));
    this._text_205 = this.renderer.createText(this._el_199,'\n		',(null as any));
    this._el_206 = import3.createRenderElement(this.renderer,this._el_199,'div',new import3.InlineArray2(2,'class','col-sm-8 col-xs-12 sl-tr-rel'),(null as any));
    this._text_207 = this.renderer.createText(this._el_206,'\n			',(null as any));
    this._el_208 = import3.createRenderElement(this.renderer,this._el_206,'div',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_209 = this.renderer.createText(this._el_208,'\n				',(null as any));
    this._el_210 = import3.createRenderElement(this.renderer,this._el_208,'div',new import3.InlineArray2(2,'class','text-right'),(null as any));
    this._text_211 = this.renderer.createText(this._el_210,'\n					',(null as any));
    this._el_212 = import3.createRenderElement(this.renderer,this._el_210,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-quote-right'),(null as any));
    this._text_213 = this.renderer.createText(this._el_210,'\n				',(null as any));
    this._text_214 = this.renderer.createText(this._el_208,'\n				',(null as any));
    this._el_215 = import3.createRenderElement(this.renderer,this._el_208,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_216 = this.renderer.createText(this._el_215,'В открытый грунт пересаживайте в пасмурную погоду, в теплицу – вечером.\n				',(null as any));
    this._text_217 = this.renderer.createText(this._el_208,'\n				',(null as any));
    this._el_218 = import3.createRenderElement(this.renderer,this._el_208,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_219 = this.renderer.createText(this._el_218,'\n					Если погода после посадки ясная, притените высаженные растения от попадания прямых солнечных лучей на 2-3 дня.\n				',(null as any));
    this._text_220 = this.renderer.createText(this._el_208,'\n				',(null as any));
    this._el_221 = import3.createRenderElement(this.renderer,this._el_208,'div',new import3.InlineArray2(2,'class','text-left'),(null as any));
    this._text_222 = this.renderer.createText(this._el_221,'\n					',(null as any));
    this._el_223 = import3.createRenderElement(this.renderer,this._el_221,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-quote-right'),(null as any));
    this._text_224 = this.renderer.createText(this._el_221,'\n				',(null as any));
    this._text_225 = this.renderer.createText(this._el_208,'\n			',(null as any));
    this._text_226 = this.renderer.createText(this._el_206,'\n		',(null as any));
    this._text_227 = this.renderer.createText(this._el_199,'\n		',(null as any));
    this._el_228 = import3.createRenderElement(this.renderer,this._el_199,'div',new import3.InlineArray2(2,'class','col-sm-2 hidden-xs'),(null as any));
    this._text_229 = this.renderer.createText(this._el_228,'\n			',(null as any));
    this._el_230 = import3.createRenderElement(this.renderer,this._el_228,'div',new import3.InlineArray2(2,'class','rassada-img rassada-img-down'),(null as any));
    this._text_231 = this.renderer.createText(this._el_228,'\n		',(null as any));
    this._text_232 = this.renderer.createText(this._el_199,'\n	',(null as any));
    this._text_233 = this.renderer.createText(this._el_197,'\n',(null as any));
    this._text_234 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_235 = import3.createRenderElement(this.renderer,parentRenderNode,'section',new import3.InlineArray4(4,'class','rassadi-section','id','Rassadi'),(null as any));
    this._text_236 = this.renderer.createText(this._el_235,'\n	',(null as any));
    this._el_237 = import3.createRenderElement(this.renderer,this._el_235,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_238 = this.renderer.createText(this._el_237,'\n		',(null as any));
    this._el_239 = import3.createRenderElement(this.renderer,this._el_237,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_240 = this.renderer.createText(this._el_239,'\n			',(null as any));
    this._el_241 = import3.createRenderElement(this.renderer,this._el_239,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_242 = this.renderer.createText(this._el_241,'Рассады Помидор',(null as any));
    this._text_243 = this.renderer.createText(this._el_239,'\n			',(null as any));
    this._el_244 = import3.createRenderElement(this.renderer,this._el_239,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_245 = this.renderer.createText(this._el_244,'\n				',(null as any));
    this._el_246 = import3.createRenderElement(this.renderer,this._el_244,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_247 = this.renderer.createText(this._el_246,'\n				',(null as any));
    this._anchor_248 = this.renderer.createTemplateAnchor(this._el_246,(null as any));
    this._vc_248 = new import11.ViewContainer(248,246,this,this._anchor_248);
    this._TemplateRef_248_5 = new import14.TemplateRef_(this,248,this._anchor_248);
    this._NgFor_248_6 = new import22.Wrapper_NgFor(this._vc_248.vcRef,this._TemplateRef_248_5,this.parentView.injectorGet(import24.IterableDiffers,this.parentIndex),this.ref);
    this._text_249 = this.renderer.createText(this._el_246,'\n				',(null as any));
    this._text_250 = this.renderer.createText(this._el_244,'\n			',(null as any));
    this._text_251 = this.renderer.createText(this._el_239,'\n		',(null as any));
    this._text_252 = this.renderer.createText(this._el_237,'\n	',(null as any));
    this._text_253 = this.renderer.createText(this._el_235,'\n',(null as any));
    this._text_254 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_255 = import3.createRenderElement(this.renderer,parentRenderNode,'section',new import3.InlineArray2(2,'class','our-number'),(null as any));
    this._text_256 = this.renderer.createText(this._el_255,'\n	',(null as any));
    this._el_257 = import3.createRenderElement(this.renderer,this._el_255,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_258 = this.renderer.createText(this._el_257,'\n		',(null as any));
    this._el_259 = import3.createRenderElement(this.renderer,this._el_257,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_260 = this.renderer.createText(this._el_259,'\n			',(null as any));
    this._el_261 = import3.createRenderElement(this.renderer,this._el_259,'div',new import3.InlineArray2(2,'class','tom-container'),(null as any));
    this._text_262 = this.renderer.createText(this._el_261,'\n				',(null as any));
    this._el_263 = import3.createRenderElement(this.renderer,this._el_261,'div',new import3.InlineArray2(2,'class','col-sm-2 hidden-xs'),(null as any));
    this._text_264 = this.renderer.createText(this._el_263,'\n					',(null as any));
    this._el_265 = import3.createRenderElement(this.renderer,this._el_263,'div',new import3.InlineArray2(2,'class','rassada-img rassada-img-up'),(null as any));
    this._text_266 = this.renderer.createText(this._el_263,'\n				',(null as any));
    this._text_267 = this.renderer.createText(this._el_261,'\n				',(null as any));
    this._el_268 = import3.createRenderElement(this.renderer,this._el_261,'div',new import3.InlineArray2(2,'class','col-sm-8 col-xs-12'),(null as any));
    this._text_269 = this.renderer.createText(this._el_268,'\n					',(null as any));
    this._el_270 = import3.createRenderElement(this.renderer,this._el_268,'div',new import3.InlineArray2(2,'class','text-left'),(null as any));
    this._text_271 = this.renderer.createText(this._el_270,'\n						',(null as any));
    this._el_272 = import3.createRenderElement(this.renderer,this._el_270,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_273 = this.renderer.createText(this._el_272,'Наши цифры',(null as any));
    this._text_274 = this.renderer.createText(this._el_270,'\n						',(null as any));
    this._el_275 = import3.createRenderElement(this.renderer,this._el_270,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_276 = this.renderer.createText(this._el_275,'\n							',(null as any));
    this._el_277 = import3.createRenderElement(this.renderer,this._el_275,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_278 = this.renderer.createText(this._el_277,'\n								',(null as any));
    this._el_279 = import3.createRenderElement(this.renderer,this._el_277,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_280 = this.renderer.createText(this._el_279,'\n									',(null as any));
    this._el_281 = import3.createRenderElement(this.renderer,this._el_279,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_282 = this.renderer.createText(this._el_281,'\n										',(null as any));
    this._el_283 = import3.createRenderElement(this.renderer,this._el_281,'div',new import3.InlineArray2(2,'class','col-sm-6'),(null as any));
    this._text_284 = this.renderer.createText(this._el_283,'\n											',(null as any));
    this._el_285 = import3.createRenderElement(this.renderer,this._el_283,'p',new import3.InlineArray2(2,'class','text-right'),(null as any));
    this._text_286 = this.renderer.createText(this._el_285,'10000 посаженных растений',(null as any));
    this._text_287 = this.renderer.createText(this._el_283,'\n										',(null as any));
    this._text_288 = this.renderer.createText(this._el_281,'\n										',(null as any));
    this._el_289 = import3.createRenderElement(this.renderer,this._el_281,'div',new import3.InlineArray2(2,'class','col-sm-6'),(null as any));
    this._text_290 = this.renderer.createText(this._el_289,'\n											',(null as any));
    this._el_291 = import3.createRenderElement(this.renderer,this._el_289,'div',new import3.InlineArray2(2,'class','progress'),(null as any));
    this._el_292 = import3.createRenderElement(this.renderer,this._el_291,'div',new import3.InlineArray4(4,'class','progress-bar','style','width: 100%'),(null as any));
    this._text_293 = this.renderer.createText(this._el_291,'\n											',(null as any));
    this._text_294 = this.renderer.createText(this._el_289,'\n										',(null as any));
    this._text_295 = this.renderer.createText(this._el_281,'\n									',(null as any));
    this._text_296 = this.renderer.createText(this._el_279,'\n								',(null as any));
    this._text_297 = this.renderer.createText(this._el_277,'\n							',(null as any));
    this._text_298 = this.renderer.createText(this._el_275,'\n\n							',(null as any));
    this._el_299 = import3.createRenderElement(this.renderer,this._el_275,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_300 = this.renderer.createText(this._el_299,'\n								',(null as any));
    this._el_301 = import3.createRenderElement(this.renderer,this._el_299,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_302 = this.renderer.createText(this._el_301,'\n									',(null as any));
    this._el_303 = import3.createRenderElement(this.renderer,this._el_301,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_304 = this.renderer.createText(this._el_303,'\n										',(null as any));
    this._el_305 = import3.createRenderElement(this.renderer,this._el_303,'div',new import3.InlineArray2(2,'class','col-sm-6'),(null as any));
    this._text_306 = this.renderer.createText(this._el_305,'\n											',(null as any));
    this._el_307 = import3.createRenderElement(this.renderer,this._el_305,'p',new import3.InlineArray2(2,'class','text-right'),(null as any));
    this._text_308 = this.renderer.createText(this._el_307,'1000 измерений для поиска оптимального решения по росту',(null as any));
    this._text_309 = this.renderer.createText(this._el_305,'\n										',(null as any));
    this._text_310 = this.renderer.createText(this._el_303,'\n										',(null as any));
    this._el_311 = import3.createRenderElement(this.renderer,this._el_303,'div',new import3.InlineArray2(2,'class','col-sm-6'),(null as any));
    this._text_312 = this.renderer.createText(this._el_311,'\n											',(null as any));
    this._el_313 = import3.createRenderElement(this.renderer,this._el_311,'div',new import3.InlineArray2(2,'class','progress'),(null as any));
    this._el_314 = import3.createRenderElement(this.renderer,this._el_313,'div',new import3.InlineArray4(4,'class','progress-bar','style','width: 50%'),(null as any));
    this._text_315 = this.renderer.createText(this._el_313,'\n											',(null as any));
    this._text_316 = this.renderer.createText(this._el_311,'\n										',(null as any));
    this._text_317 = this.renderer.createText(this._el_303,'\n									',(null as any));
    this._text_318 = this.renderer.createText(this._el_301,'\n								',(null as any));
    this._text_319 = this.renderer.createText(this._el_299,'\n							',(null as any));
    this._text_320 = this.renderer.createText(this._el_275,'\n\n							',(null as any));
    this._el_321 = import3.createRenderElement(this.renderer,this._el_275,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_322 = this.renderer.createText(this._el_321,'\n								',(null as any));
    this._el_323 = import3.createRenderElement(this.renderer,this._el_321,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_324 = this.renderer.createText(this._el_323,'\n									',(null as any));
    this._el_325 = import3.createRenderElement(this.renderer,this._el_323,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_326 = this.renderer.createText(this._el_325,'\n										',(null as any));
    this._el_327 = import3.createRenderElement(this.renderer,this._el_325,'div',new import3.InlineArray2(2,'class','col-sm-6'),(null as any));
    this._text_328 = this.renderer.createText(this._el_327,'\n											',(null as any));
    this._el_329 = import3.createRenderElement(this.renderer,this._el_327,'p',new import3.InlineArray2(2,'class','text-right'),(null as any));
    this._text_330 = this.renderer.createText(this._el_329,'1000 проверенных сортов семян',(null as any));
    this._text_331 = this.renderer.createText(this._el_327,'\n										',(null as any));
    this._text_332 = this.renderer.createText(this._el_325,'\n										',(null as any));
    this._el_333 = import3.createRenderElement(this.renderer,this._el_325,'div',new import3.InlineArray2(2,'class','col-sm-6'),(null as any));
    this._text_334 = this.renderer.createText(this._el_333,'\n											',(null as any));
    this._el_335 = import3.createRenderElement(this.renderer,this._el_333,'div',new import3.InlineArray2(2,'class','progress'),(null as any));
    this._el_336 = import3.createRenderElement(this.renderer,this._el_335,'div',new import3.InlineArray4(4,'class','progress-bar','style','width: 50%'),(null as any));
    this._text_337 = this.renderer.createText(this._el_335,'\n											',(null as any));
    this._text_338 = this.renderer.createText(this._el_333,'\n										',(null as any));
    this._text_339 = this.renderer.createText(this._el_325,'\n									',(null as any));
    this._text_340 = this.renderer.createText(this._el_323,'\n								',(null as any));
    this._text_341 = this.renderer.createText(this._el_321,'\n							',(null as any));
    this._text_342 = this.renderer.createText(this._el_275,'\n\n							',(null as any));
    this._el_343 = import3.createRenderElement(this.renderer,this._el_275,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_344 = this.renderer.createText(this._el_343,'\n								',(null as any));
    this._el_345 = import3.createRenderElement(this.renderer,this._el_343,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_346 = this.renderer.createText(this._el_345,'\n									',(null as any));
    this._el_347 = import3.createRenderElement(this.renderer,this._el_345,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_348 = this.renderer.createText(this._el_347,'\n										',(null as any));
    this._el_349 = import3.createRenderElement(this.renderer,this._el_347,'div',new import3.InlineArray2(2,'class','col-sm-6'),(null as any));
    this._text_350 = this.renderer.createText(this._el_349,'\n											',(null as any));
    this._el_351 = import3.createRenderElement(this.renderer,this._el_349,'p',new import3.InlineArray2(2,'class','text-right'),(null as any));
    this._text_352 = this.renderer.createText(this._el_351,'100 тонн плодоротной почвы и удобрений',(null as any));
    this._text_353 = this.renderer.createText(this._el_349,'\n										',(null as any));
    this._text_354 = this.renderer.createText(this._el_347,'\n										',(null as any));
    this._el_355 = import3.createRenderElement(this.renderer,this._el_347,'div',new import3.InlineArray2(2,'class','col-sm-6'),(null as any));
    this._text_356 = this.renderer.createText(this._el_355,'\n											',(null as any));
    this._el_357 = import3.createRenderElement(this.renderer,this._el_355,'div',new import3.InlineArray2(2,'class','progress'),(null as any));
    this._el_358 = import3.createRenderElement(this.renderer,this._el_357,'div',new import3.InlineArray4(4,'class','progress-bar','style','width: 25%'),(null as any));
    this._text_359 = this.renderer.createText(this._el_357,'\n											',(null as any));
    this._text_360 = this.renderer.createText(this._el_355,'\n										',(null as any));
    this._text_361 = this.renderer.createText(this._el_347,'\n									',(null as any));
    this._text_362 = this.renderer.createText(this._el_345,'\n								',(null as any));
    this._text_363 = this.renderer.createText(this._el_343,'\n							',(null as any));
    this._text_364 = this.renderer.createText(this._el_275,'\n\n						',(null as any));
    this._text_365 = this.renderer.createText(this._el_270,'\n					',(null as any));
    this._text_366 = this.renderer.createText(this._el_268,'\n				',(null as any));
    this._text_367 = this.renderer.createText(this._el_261,'\n				',(null as any));
    this._el_368 = import3.createRenderElement(this.renderer,this._el_261,'div',new import3.InlineArray2(2,'class','col-sm-2 hidden-xs'),(null as any));
    this._text_369 = this.renderer.createText(this._el_368,'\n					',(null as any));
    this._el_370 = import3.createRenderElement(this.renderer,this._el_368,'div',new import3.InlineArray2(2,'class','rassada-img rassada-img-down'),(null as any));
    this._text_371 = this.renderer.createText(this._el_368,'\n				',(null as any));
    this._text_372 = this.renderer.createText(this._el_261,'\n			',(null as any));
    this._text_373 = this.renderer.createText(this._el_259,'\n		',(null as any));
    this._text_374 = this.renderer.createText(this._el_257,'\n	',(null as any));
    this._text_375 = this.renderer.createText(this._el_255,'\n',(null as any));
    this._text_376 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_377 = import3.createRenderElement(this.renderer,parentRenderNode,'section',new import3.InlineArray2(2,'class','our-work'),(null as any));
    this._text_378 = this.renderer.createText(this._el_377,'\n	',(null as any));
    this._el_379 = import3.createRenderElement(this.renderer,this._el_377,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_380 = this.renderer.createText(this._el_379,'\n		',(null as any));
    this._el_381 = import3.createRenderElement(this.renderer,this._el_379,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_382 = this.renderer.createText(this._el_381,'\n			',(null as any));
    this._el_383 = import3.createRenderElement(this.renderer,this._el_381,'div',new import3.InlineArray2(2,'class','col-xs-12 h2-left'),(null as any));
    this._text_384 = this.renderer.createText(this._el_383,'\n				',(null as any));
    this._el_385 = import3.createRenderElement(this.renderer,this._el_383,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_386 = this.renderer.createText(this._el_385,'Как мы работаем',(null as any));
    this._text_387 = this.renderer.createText(this._el_383,'\n			',(null as any));
    this._text_388 = this.renderer.createText(this._el_381,'\n			',(null as any));
    this._el_389 = import3.createRenderElement(this.renderer,this._el_381,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_390 = this.renderer.createText(this._el_389,'\n				',(null as any));
    this._el_391 = import3.createRenderElement(this.renderer,this._el_389,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_392 = this.renderer.createText(this._el_391,'\n					\n					',(null as any));
    this._el_393 = import3.createRenderElement(this.renderer,this._el_391,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-3 text-center'),(null as any));
    this._text_394 = this.renderer.createText(this._el_393,'\n						',(null as any));
    this._el_395 = import3.createRenderElement(this.renderer,this._el_393,'img',new import3.InlineArray4(4,'alt','','src','./image/OurWork/semena.svg'),(null as any));
    this._text_396 = this.renderer.createText(this._el_393,'\n						',(null as any));
    this._el_397 = import3.createRenderElement(this.renderer,this._el_393,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_398 = this.renderer.createText(this._el_393,'\n						',(null as any));
    this._el_399 = import3.createRenderElement(this.renderer,this._el_393,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_400 = this.renderer.createText(this._el_399,'Все начинается с тщательного и правильного выбора семян',(null as any));
    this._text_401 = this.renderer.createText(this._el_393,'\n					',(null as any));
    this._text_402 = this.renderer.createText(this._el_391,'\n					',(null as any));
    this._el_403 = import3.createRenderElement(this.renderer,this._el_391,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-3 text-center'),(null as any));
    this._text_404 = this.renderer.createText(this._el_403,'\n						',(null as any));
    this._el_405 = import3.createRenderElement(this.renderer,this._el_403,'img',new import3.InlineArray4(4,'alt','','src','./image/OurWork/udobreniya.svg'),(null as any));
    this._text_406 = this.renderer.createText(this._el_403,'\n						',(null as any));
    this._el_407 = import3.createRenderElement(this.renderer,this._el_403,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_408 = this.renderer.createText(this._el_403,'\n						',(null as any));
    this._el_409 = import3.createRenderElement(this.renderer,this._el_403,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_410 = this.renderer.createText(this._el_409,'Выбор грунта и удобрений',(null as any));
    this._text_411 = this.renderer.createText(this._el_403,'\n					',(null as any));
    this._text_412 = this.renderer.createText(this._el_391,'\n					',(null as any));
    this._el_413 = import3.createRenderElement(this.renderer,this._el_391,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-3 text-center'),(null as any));
    this._text_414 = this.renderer.createText(this._el_413,'\n						',(null as any));
    this._el_415 = import3.createRenderElement(this.renderer,this._el_413,'img',new import3.InlineArray4(4,'alt','','src','./image/OurWork/usloviya.svg'),(null as any));
    this._text_416 = this.renderer.createText(this._el_413,'\n						',(null as any));
    this._el_417 = import3.createRenderElement(this.renderer,this._el_413,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_418 = this.renderer.createText(this._el_413,'\n						',(null as any));
    this._el_419 = import3.createRenderElement(this.renderer,this._el_413,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_420 = this.renderer.createText(this._el_419,'Выбор оптимальных параметров среды: тем-ра воздуха, тем-ра почвы, влажность почвы, влажность воздуха, освещение',(null as any));
    this._text_421 = this.renderer.createText(this._el_413,'\n					',(null as any));
    this._text_422 = this.renderer.createText(this._el_391,'\n					',(null as any));
    this._el_423 = import3.createRenderElement(this.renderer,this._el_391,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-3 text-center'),(null as any));
    this._text_424 = this.renderer.createText(this._el_423,'\n						',(null as any));
    this._el_425 = import3.createRenderElement(this.renderer,this._el_423,'img',new import3.InlineArray4(4,'alt','','src','./image/OurWork/rassada.svg'),(null as any));
    this._text_426 = this.renderer.createText(this._el_423,'\n						',(null as any));
    this._el_427 = import3.createRenderElement(this.renderer,this._el_423,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_428 = this.renderer.createText(this._el_423,'\n						',(null as any));
    this._el_429 = import3.createRenderElement(this.renderer,this._el_423,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_430 = this.renderer.createText(this._el_429,'На выходе мы получаем лучшие сорта рассад и результат наличие большого урожая',(null as any));
    this._text_431 = this.renderer.createText(this._el_423,'\n					',(null as any));
    this._text_432 = this.renderer.createText(this._el_391,'\n				',(null as any));
    this._text_433 = this.renderer.createText(this._el_389,'\n			',(null as any));
    this._text_434 = this.renderer.createText(this._el_381,'\n		',(null as any));
    this._text_435 = this.renderer.createText(this._el_379,'\n	',(null as any));
    this._text_436 = this.renderer.createText(this._el_377,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_133,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_133));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_147,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_147));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_152,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_152));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_173,new import3.InlineArray8(8,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any),'change',(null as any)),this.eventHandler(this.handleEvent_173));
    this._NgModel_173_6.subscribe(this,this.eventHandler(this.handleEvent_173),true);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_183,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_183));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._text_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._el_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._text_103,
      this._el_104,
      this._text_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._text_109,
      this._text_110,
      this._text_111,
      this._text_112,
      this._text_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._el_117,
      this._text_118,
      this._text_119,
      this._text_120,
      this._text_121,
      this._el_122,
      this._text_123,
      this._el_124,
      this._text_125,
      this._el_126,
      this._text_127,
      this._el_128,
      this._text_129,
      this._text_130,
      this._el_131,
      this._text_132,
      this._el_133,
      this._text_134,
      this._el_135,
      this._text_136,
      this._el_137,
      this._text_138,
      this._text_139,
      this._el_140,
      this._text_141,
      this._el_142,
      this._text_143,
      this._text_144,
      this._el_145,
      this._text_146,
      this._el_147,
      this._text_148,
      this._el_149,
      this._text_150,
      this._text_151,
      this._el_152,
      this._text_153,
      this._el_154,
      this._text_155,
      this._text_156,
      this._el_157,
      this._text_158,
      this._el_159,
      this._text_160,
      this._el_161,
      this._text_162,
      this._text_163,
      this._text_164,
      this._text_165,
      this._text_166,
      this._text_167,
      this._el_168,
      this._text_169,
      this._el_170,
      this._text_171,
      this._text_172,
      this._el_173,
      this._text_174,
      this._el_175,
      this._text_176,
      this._el_177,
      this._text_178,
      this._text_179,
      this._el_180,
      this._text_181,
      this._text_182,
      this._el_183,
      this._text_184,
      this._el_185,
      this._text_186,
      this._text_187,
      this._anchor_188,
      this._text_189,
      this._text_190,
      this._text_191,
      this._text_192,
      this._text_193,
      this._text_194,
      this._text_195,
      this._text_196,
      this._el_197,
      this._text_198,
      this._el_199,
      this._text_200,
      this._el_201,
      this._text_202,
      this._el_203,
      this._text_204,
      this._text_205,
      this._el_206,
      this._text_207,
      this._el_208,
      this._text_209,
      this._el_210,
      this._text_211,
      this._el_212,
      this._text_213,
      this._text_214,
      this._el_215,
      this._text_216,
      this._text_217,
      this._el_218,
      this._text_219,
      this._text_220,
      this._el_221,
      this._text_222,
      this._el_223,
      this._text_224,
      this._text_225,
      this._text_226,
      this._text_227,
      this._el_228,
      this._text_229,
      this._el_230,
      this._text_231,
      this._text_232,
      this._text_233,
      this._text_234,
      this._el_235,
      this._text_236,
      this._el_237,
      this._text_238,
      this._el_239,
      this._text_240,
      this._el_241,
      this._text_242,
      this._text_243,
      this._el_244,
      this._text_245,
      this._el_246,
      this._text_247,
      this._anchor_248,
      this._text_249,
      this._text_250,
      this._text_251,
      this._text_252,
      this._text_253,
      this._text_254,
      this._el_255,
      this._text_256,
      this._el_257,
      this._text_258,
      this._el_259,
      this._text_260,
      this._el_261,
      this._text_262,
      this._el_263,
      this._text_264,
      this._el_265,
      this._text_266,
      this._text_267,
      this._el_268,
      this._text_269,
      this._el_270,
      this._text_271,
      this._el_272,
      this._text_273,
      this._text_274,
      this._el_275,
      this._text_276,
      this._el_277,
      this._text_278,
      this._el_279,
      this._text_280,
      this._el_281,
      this._text_282,
      this._el_283,
      this._text_284,
      this._el_285,
      this._text_286,
      this._text_287,
      this._text_288,
      this._el_289,
      this._text_290,
      this._el_291,
      this._el_292,
      this._text_293,
      this._text_294,
      this._text_295,
      this._text_296,
      this._text_297,
      this._text_298,
      this._el_299,
      this._text_300,
      this._el_301,
      this._text_302,
      this._el_303,
      this._text_304,
      this._el_305,
      this._text_306,
      this._el_307,
      this._text_308,
      this._text_309,
      this._text_310,
      this._el_311,
      this._text_312,
      this._el_313,
      this._el_314,
      this._text_315,
      this._text_316,
      this._text_317,
      this._text_318,
      this._text_319,
      this._text_320,
      this._el_321,
      this._text_322,
      this._el_323,
      this._text_324,
      this._el_325,
      this._text_326,
      this._el_327,
      this._text_328,
      this._el_329,
      this._text_330,
      this._text_331,
      this._text_332,
      this._el_333,
      this._text_334,
      this._el_335,
      this._el_336,
      this._text_337,
      this._text_338,
      this._text_339,
      this._text_340,
      this._text_341,
      this._text_342,
      this._el_343,
      this._text_344,
      this._el_345,
      this._text_346,
      this._el_347,
      this._text_348,
      this._el_349,
      this._text_350,
      this._el_351,
      this._text_352,
      this._text_353,
      this._text_354,
      this._el_355,
      this._text_356,
      this._el_357,
      this._el_358,
      this._text_359,
      this._text_360,
      this._text_361,
      this._text_362,
      this._text_363,
      this._text_364,
      this._text_365,
      this._text_366,
      this._text_367,
      this._el_368,
      this._text_369,
      this._el_370,
      this._text_371,
      this._text_372,
      this._text_373,
      this._text_374,
      this._text_375,
      this._text_376,
      this._el_377,
      this._text_378,
      this._el_379,
      this._text_380,
      this._el_381,
      this._text_382,
      this._el_383,
      this._text_384,
      this._el_385,
      this._text_386,
      this._text_387,
      this._text_388,
      this._el_389,
      this._text_390,
      this._el_391,
      this._text_392,
      this._el_393,
      this._text_394,
      this._el_395,
      this._text_396,
      this._el_397,
      this._text_398,
      this._el_399,
      this._text_400,
      this._text_401,
      this._text_402,
      this._el_403,
      this._text_404,
      this._el_405,
      this._text_406,
      this._el_407,
      this._text_408,
      this._el_409,
      this._text_410,
      this._text_411,
      this._text_412,
      this._el_413,
      this._text_414,
      this._el_415,
      this._text_416,
      this._el_417,
      this._text_418,
      this._el_419,
      this._text_420,
      this._text_421,
      this._text_422,
      this._el_423,
      this._text_424,
      this._el_425,
      this._text_426,
      this._el_427,
      this._text_428,
      this._el_429,
      this._text_430,
      this._text_431,
      this._text_432,
      this._text_433,
      this._text_434,
      this._text_435,
      this._text_436
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.DefaultValueAccessor) && (173 === requestNodeIndex))) { return this._DefaultValueAccessor_173_3.context; }
    if (((token === import26.NumberValueAccessor) && (173 === requestNodeIndex))) { return this._NumberValueAccessor_173_4.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (173 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_173_5; }
    if (((token === import28.NgModel) && (173 === requestNodeIndex))) { return this._NgModel_173_6.context; }
    if (((token === import29.NgControl) && (173 === requestNodeIndex))) { return this._NgControl_173_7; }
    if (((token === import30.NgControlStatus) && (173 === requestNodeIndex))) { return this._NgControlStatus_173_8.context; }
    if (((token === import14.TemplateRef) && (188 === requestNodeIndex))) { return this._TemplateRef_188_5; }
    if (((token === import15.NgIf) && (188 === requestNodeIndex))) { return this._NgIf_188_6.context; }
    if (((token === import31.NgForm) && ((133 <= requestNodeIndex) && (requestNodeIndex <= 191)))) { return this._NgForm_133_3.context; }
    if (((token === import32.ControlContainer) && ((133 <= requestNodeIndex) && (requestNodeIndex <= 191)))) { return this._ControlContainer_133_4; }
    if (((token === import30.NgControlStatusGroup) && ((133 <= requestNodeIndex) && (requestNodeIndex <= 191)))) { return this._NgControlStatusGroup_133_5.context; }
    if (((token === import14.TemplateRef) && (248 === requestNodeIndex))) { return this._TemplateRef_248_5; }
    if (((token === import33.NgFor) && (248 === requestNodeIndex))) { return this._NgFor_248_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_133_3.ngDoCheck(this,this._el_133,throwOnChange);
    this._NgControlStatusGroup_133_5.ngDoCheck(this,this._el_133,throwOnChange);
    this._DefaultValueAccessor_173_3.ngDoCheck(this,this._el_173,throwOnChange);
    this._NumberValueAccessor_173_4.ngDoCheck(this,this._el_173,throwOnChange);
    const currVal_173_2_0:any = 'rasCount';
    this._NgModel_173_6.check_name(currVal_173_2_0,throwOnChange,false);
    const currVal_173_2_1:any = this.context.rasCount;
    this._NgModel_173_6.check_model(currVal_173_2_1,throwOnChange,false);
    this._NgModel_173_6.ngDoCheck(this,this._el_173,throwOnChange);
    this._NgControlStatus_173_8.ngDoCheck(this,this._el_173,throwOnChange);
    const currVal_188_0_0:any = this.context.isSpecial;
    this._NgIf_188_6.check_ngIf(currVal_188_0_0,throwOnChange,false);
    this._NgIf_188_6.ngDoCheck(this,this._anchor_188,throwOnChange);
    const currVal_248_0_0:any = this.context.gallerys;
    this._NgFor_248_6.check_ngForOf(currVal_248_0_0,throwOnChange,false);
    this._NgFor_248_6.ngDoCheck(this,this._anchor_248,throwOnChange);
    this._vc_188.detectChangesInNestedViews(throwOnChange);
    this._vc_248.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_133_5.checkHost(this,this,this._el_133,throwOnChange);
    const currVal_452:any = import3.inlineInterpolate(1,'',this.context.imgPath,'');
    if (import3.checkBinding(throwOnChange,this._expr_452,currVal_452)) {
      this.renderer.setElementProperty(this._el_159,'src',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_452));
      this._expr_452 = currVal_452;
    }
    const currVal_453:any = import3.inlineInterpolate(1,'',this.context.shCart.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_453,currVal_453)) {
      this.renderer.setText(this._text_162,currVal_453);
      this._expr_453 = currVal_453;
    }
    this._NgControlStatus_173_8.checkHost(this,this,this._el_173,throwOnChange);
    const currVal_454:any = import3.inlineInterpolate(1,'\n										',this.context.shCart.price,' ');
    if (import3.checkBinding(throwOnChange,this._expr_454,currVal_454)) {
      this.renderer.setText(this._text_176,currVal_454);
      this._expr_454 = currVal_454;
    }
  }
  destroyInternal():void {
    this._vc_188.destroyNestedViews();
    this._vc_248.destroyNestedViews();
    this._NgModel_173_6.ngOnDestroy();
    this._NgForm_133_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 188)) { return new View_SectionComponent1(this.viewUtils,this,188,this._anchor_188,this._vc_188); }
    if ((nodeIndex == 248)) { return new View_SectionComponent2(this.viewUtils,this,248,this._anchor_248,this._vc_248); }
    return (null as any);
  }
  handleEvent_133(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_133_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_147(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.plusDivs((0 - 1))) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_152(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.plusDivs(1)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_173(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_173_3.handleEvent(eventName,$event) && result);
    result = (this._NumberValueAccessor_173_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.rasCount = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_183(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.shopCartClick()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}