/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.panel-body, .list-group-item\n	background: linear-gradient(to left,  rgba(0, 173, 76, 1), #007031)\n\n.btn-success\n	background: #007031\n\n.shop-section\n	margin: 20px 5px 0 5px'];